var TRANSLATIONS = {
    en: {
        title: "Photo geolocator",
        welcome: "Welcome! Upload a photo to identify where it was taken.",
        upload: "Upload photo",
        searching: "Identifying location...",
        view: "View",
        theme: "Theme",
        language: "Language",
        satellite: "Satellite",
        street: "Street",
        dark: "Dark",
        light: "Light",
        unknownLocation: "The location of this photo could not be identified",
        unknownLocationShort: "Unknown location",
        photoTakenIn: "This photo was taken in {place}",
        methodGPS: "Location identified using GPS coordinates from photo metadata.",
        moreInformation: "Learn more",
    },

    ar: {
        title: "محدد موقع الصور",
        welcome: "مرحبًا! قم بتحميل صورة لتحديد مكان التقاطها.",
        upload: "تحميل صورة",
        searching: "جارٍ تحديد الموقع...",
        view: "العرض",
        theme: "المظهر",
        language: "اللغة",
        satellite: "القمر الصناعي",
        street: "الشارع",
        dark: "داكن",
        light: "فاتح",
        unknownLocation: "تعذر تحديد موقع هذه الصورة",
        unknownLocationShort: "موقع غير معروف",
        photoTakenIn: "تم التقاط هذه الصورة في {place}",
        methodGPS: "تم تحديد الموقع باستخدام إحداثيات GPS من بيانات الصورة.",
        moreInformation: "مزيد من المعلومات",
    },

    bg: {
        title: "Геолокатор на снимки",
        welcome: "Добре дошли! Качете снимка, за да определите къде е направена.",
        upload: "Качване на снимка",
        searching: "Определяне на местоположението...",
        view: "Изглед",
        theme: "Тема",
        language: "Език",
        satellite: "Сателит",
        street: "Улица",
        dark: "Тъмна",
        light: "Светла",
        unknownLocation: "Местоположението на тази снимка не можа да бъде определено",
        unknownLocationShort: "Неизвестно местоположение",
        photoTakenIn: "Тази снимка е направена в {place}",
        methodGPS: "Местоположението е определено чрез GPS координатите в метаданните на снимката.",
        moreInformation: "Научете повече",
    },

    bn: {
        title: "ছবির অবস্থান নির্ধারক",
        welcome: "স্বাগতম! ছবিটি কোথায় তোলা হয়েছে তা শনাক্ত করতে একটি ছবি আপলোড করুন।",
        upload: "ছবি আপলোড করুন",
        searching: "অবস্থান শনাক্ত করা হচ্ছে...",
        view: "ভিউ",
        theme: "থিম",
        language: "ভাষা",
        satellite: "স্যাটেলাইট",
        street: "রাস্তা",
        dark: "ডার্ক",
        light: "লাইট",
        unknownLocation: "এই ছবির অবস্থান শনাক্ত করা যায়নি",
        unknownLocationShort: "অজানা অবস্থান",
        photoTakenIn: "এই ছবিটি {place}-এ তোলা হয়েছে",
        methodGPS: "ছবির মেটাডেটার GPS স্থানাঙ্ক ব্যবহার করে অবস্থান শনাক্ত করা হয়েছে।",
        moreInformation: "আরও জানুন",
    },

    cs: {
        title: "Geolokátor fotografií",
        welcome: "Vítejte! Nahrajte fotografii a zjistěte, kde byla pořízena.",
        upload: "Nahrát fotografii",
        searching: "Určování polohy...",
        view: "Pohled",
        theme: "Motiv",
        language: "Jazyk",
        satellite: "Satelit",
        street: "Ulice",
        dark: "Tmavý",
        light: "Světlý",
        unknownLocation: "Místo této fotografie se nepodařilo určit",
        unknownLocationShort: "Neznámé místo",
        photoTakenIn: "Tato fotografie byla pořízena v {place}",
        methodGPS: "Poloha byla určena pomocí GPS souřadnic z metadat fotografie.",
        moreInformation: "Zjistit více",
    },

    da: {
        title: "Billedgeolokator",
        welcome: "Velkommen! Upload et billede for at identificere, hvor det blev taget.",
        upload: "Upload billede",
        searching: "Identificerer placering...",
        view: "Visning",
        theme: "Tema",
        language: "Sprog",
        satellite: "Satellit",
        street: "Gade",
        dark: "Mørk",
        light: "Lys",
        unknownLocation: "Placeringen af dette billede kunne ikke identificeres",
        unknownLocationShort: "Ukendt placering",
        photoTakenIn: "Dette billede blev taget i {place}",
        methodGPS: "Placeringen blev identificeret ved hjælp af GPS-koordinater fra billedets metadata.",
        moreInformation: "Læs mere",
    },

    de: {
        title: "Foto-Geolokalisierer",
        welcome: "Willkommen! Laden Sie ein Foto hoch, um herauszufinden, wo es aufgenommen wurde.",
        upload: "Foto hochladen",
        searching: "Standort wird identifiziert...",
        view: "Ansicht",
        theme: "Design",
        language: "Sprache",
        satellite: "Satellit",
        street: "Straße",
        dark: "Dunkel",
        light: "Hell",
        unknownLocation: "Der Ort dieses Fotos konnte nicht identifiziert werden",
        unknownLocationShort: "Unbekannter Ort",
        photoTakenIn: "Dieses Foto wurde in {place} aufgenommen",
        methodGPS: "Der Standort wurde mithilfe der GPS-Koordinaten aus den Fotometadaten identifiziert.",
        moreInformation: "Mehr erfahren",
    },

    el: {
        title: "Γεωεντοπισμός φωτογραφιών",
        welcome: "Καλώς ήρθατε! Ανεβάστε μια φωτογραφία για να εντοπίσετε πού τραβήχτηκε.",
        upload: "Μεταφόρτωση φωτογραφίας",
        searching: "Εντοπισμός τοποθεσίας...",
        view: "Προβολή",
        theme: "Θέμα",
        language: "Γλώσσα",
        satellite: "Δορυφόρος",
        street: "Δρόμος",
        dark: "Σκούρο",
        light: "Ανοιχτό",
        unknownLocation: "Δεν ήταν δυνατός ο εντοπισμός της τοποθεσίας αυτής της φωτογραφίας",
        unknownLocationShort: "Άγνωστη τοποθεσία",
        photoTakenIn: "Αυτή η φωτογραφία τραβήχτηκε στο {place}",
        methodGPS: "Η τοποθεσία εντοπίστηκε χρησιμοποιώντας τις συντεταγμένες GPS από τα μεταδεδομένα της φωτογραφίας.",
        moreInformation: "Μάθετε περισσότερα",
    },

    es: {
        title: "Geolocalizador de fotos",
        welcome: "¡Bienvenido! Sube una foto para identificar dónde fue tomada.",
        upload: "Subir foto",
        searching: "Identificando ubicación...",
        view: "Vista",
        theme: "Tema",
        language: "Idioma",
        satellite: "Satélite",
        street: "Calle",
        dark: "Oscuro",
        light: "Claro",
        unknownLocation: "No se pudo identificar la ubicación de esta foto",
        unknownLocationShort: "Ubicación desconocida",
        photoTakenIn: "Esta foto fue tomada en {place}",
        methodGPS: "Ubicación identificada usando las coordenadas GPS de los metadatos de la foto.",
        moreInformation: "Más información",
    },

    et: {
        title: "Foto geolokaator",
        welcome: "Tere tulemast! Laadi üles foto, et tuvastada, kus see tehti.",
        upload: "Laadi foto üles",
        searching: "Asukohta tuvastatakse...",
        view: "Vaade",
        theme: "Teema",
        language: "Keel",
        satellite: "Satelliit",
        street: "Tänav",
        dark: "Tume",
        light: "Hele",
        unknownLocation: "Selle foto asukohta ei õnnestunud tuvastada",
        unknownLocationShort: "Tundmatu asukoht",
        photoTakenIn: "See foto tehti kohas {place}",
        methodGPS: "Asukoht tuvastati foto metaandmete GPS-koordinaatide abil.",
        moreInformation: "Lisateave",
    },

    fa: {
        title: "مکان‌یاب عکس",
        welcome: "خوش آمدید! یک عکس بارگذاری کنید تا محل گرفته شدن آن شناسایی شود.",
        upload: "بارگذاری عکس",
        searching: "در حال شناسایی موقعیت...",
        view: "نمایش",
        theme: "تم",
        language: "زبان",
        satellite: "ماهواره",
        street: "خیابان",
        dark: "تیره",
        light: "روشن",
        unknownLocation: "موقعیت این عکس قابل شناسایی نبود",
        unknownLocationShort: "موقعیت نامشخص",
        photoTakenIn: "این عکس در {place} گرفته شده است",
        methodGPS: "موقعیت با استفاده از مختصات GPS موجود در فراداده عکس شناسایی شد.",
        moreInformation: "اطلاعات بیشتر",
    },

    fi: {
        title: "Valokuvien paikannin",
        welcome: "Tervetuloa! Lataa kuva tunnistaaksesi, missä se otettiin.",
        upload: "Lataa kuva",
        searching: "Sijaintia tunnistetaan...",
        view: "Näkymä",
        theme: "Teema",
        language: "Kieli",
        satellite: "Satelliitti",
        street: "Katu",
        dark: "Tumma",
        light: "Vaalea",
        unknownLocation: "Tämän kuvan sijaintia ei voitu tunnistaa",
        unknownLocationShort: "Tuntematon sijainti",
        photoTakenIn: "Tämä kuva otettiin paikassa {place}",
        methodGPS: "Sijainti tunnistettiin kuvan metatiedoissa olevien GPS-koordinaattien avulla.",
        moreInformation: "Lisätietoja",
    },

    fr: {
        title: "Géolocalisateur de photo",
        welcome: "Bienvenue ! Téléchargez une photo pour identifier où elle a été prise.",
        upload: "Télécharger une photo",
        searching: "Identification du lieu...",
        view: "Vue",
        theme: "Thème",
        language: "Langue",
        satellite: "Satellite",
        street: "Rue",
        dark: "Sombre",
        light: "Clair",
        unknownLocation: "Le lieu de cette photo n'a pas pu être identifié",
        unknownLocationShort: "Lieu inconnu",
        photoTakenIn: "Cette photo a été prise à {place}",
        methodGPS: "Lieu identifié à partir des coordonnées GPS des métadonnées de la photo.",
        moreInformation: "En savoir plus",
    },

    he: {
        title: "מאתר מיקום תמונות",
        welcome: "ברוכים הבאים! העלו תמונה כדי לזהות היכן היא צולמה.",
        upload: "העלאת תמונה",
        searching: "מזהה מיקום...",
        view: "תצוגה",
        theme: "ערכת נושא",
        language: "שפה",
        satellite: "לוויין",
        street: "רחוב",
        dark: "כהה",
        light: "בהיר",
        unknownLocation: "לא ניתן היה לזהות את מיקום התמונה",
        unknownLocationShort: "מיקום לא ידוע",
        photoTakenIn: "התמונה הזו צולמה ב{place}",
        methodGPS: "המיקום זוהה באמצעות קואורדינטות GPS ממטא־הנתונים של התמונה.",
        moreInformation: "למידע נוסף",
    },

    hi: {
        title: "फोटो जियोलोकेटर",
        welcome: "स्वागत है! यह पहचानने के लिए एक फोटो अपलोड करें कि इसे कहाँ लिया गया था।",
        upload: "फोटो अपलोड करें",
        searching: "स्थान की पहचान की जा रही है...",
        view: "दृश्य",
        theme: "थीम",
        language: "भाषा",
        satellite: "सैटेलाइट",
        street: "सड़क",
        dark: "डार्क",
        light: "लाइट",
        unknownLocation: "इस फोटो का स्थान पहचाना नहीं जा सका",
        unknownLocationShort: "अज्ञात स्थान",
        photoTakenIn: "यह फोटो {place} में ली गई थी",
        methodGPS: "फोटो के मेटाडेटा में मौजूद GPS निर्देशांकों का उपयोग करके स्थान पहचाना गया।",
        moreInformation: "और जानें",
    },

    hr: {
        title: "Geolokator fotografija",
        welcome: "Dobrodošli! Prenesite fotografiju kako biste identificirali gdje je snimljena.",
        upload: "Prenesi fotografiju",
        searching: "Identificiranje lokacije...",
        view: "Prikaz",
        theme: "Tema",
        language: "Jezik",
        satellite: "Satelit",
        street: "Ulica",
        dark: "Tamna",
        light: "Svijetla",
        unknownLocation: "Lokacija ove fotografije nije mogla biti identificirana",
        unknownLocationShort: "Nepoznata lokacija",
        photoTakenIn: "Ova fotografija je snimljena u {place}",
        methodGPS: "Lokacija je identificirana pomoću GPS koordinata iz metapodataka fotografije.",
        moreInformation: "Saznaj više",
    },

    hu: {
        title: "Fotó geolokátor",
        welcome: "Üdvözöljük! Töltsön fel egy fényképet annak meghatározásához, hol készült.",
        upload: "Fotó feltöltése",
        searching: "Hely meghatározása...",
        view: "Nézet",
        theme: "Téma",
        language: "Nyelv",
        satellite: "Műhold",
        street: "Utca",
        dark: "Sötét",
        light: "Világos",
        unknownLocation: "A fénykép helyét nem sikerült azonosítani",
        unknownLocationShort: "Ismeretlen hely",
        photoTakenIn: "Ez a fénykép itt készült: {place}",
        methodGPS: "A helyet a fénykép metaadataiban található GPS-koordináták alapján azonosítottuk.",
        moreInformation: "További információ",
    },

    id: {
        title: "Pelacak lokasi foto",
        welcome: "Selamat datang! Unggah foto untuk mengidentifikasi tempat foto tersebut diambil.",
        upload: "Unggah foto",
        searching: "Mengidentifikasi lokasi...",
        view: "Tampilan",
        theme: "Tema",
        language: "Bahasa",
        satellite: "Satelit",
        street: "Jalan",
        dark: "Gelap",
        light: "Terang",
        unknownLocation: "Lokasi foto ini tidak dapat diidentifikasi",
        unknownLocationShort: "Lokasi tidak diketahui",
        photoTakenIn: "Foto ini diambil di {place}",
        methodGPS: "Lokasi diidentifikasi menggunakan koordinat GPS dari metadata foto.",
        moreInformation: "Pelajari lebih lanjut",
    },

    is: {
        title: "Landstaðsetning mynda",
        welcome: "Velkomin! Hladdu upp mynd til að finna hvar hún var tekin.",
        upload: "Hlaða upp mynd",
        searching: "Að staðsetja mynd...",
        view: "Sýn",
        theme: "Þema",
        language: "Tungumál",
        satellite: "Gervihnöttur",
        street: "Gata",
        dark: "Dökkt",
        light: "Ljóst",
        unknownLocation: "Ekki tókst að staðsetja þessa mynd",
        unknownLocationShort: "Óþekkt staðsetning",
        photoTakenIn: "Þessi mynd var tekin í {place}",
        methodGPS: "Staðsetning var fundin með GPS-hnitum úr lýsigögnum myndarinnar.",
        moreInformation: "Frekari upplýsingar",
    },

    it: {
        title: "Geolocalizzatore di foto",
        welcome: "Benvenuto! Carica una foto per identificare dove è stata scattata.",
        upload: "Carica foto",
        searching: "Identificazione della posizione...",
        view: "Vista",
        theme: "Tema",
        language: "Lingua",
        satellite: "Satellite",
        street: "Strada",
        dark: "Scuro",
        light: "Chiaro",
        unknownLocation: "Non è stato possibile identificare la posizione di questa foto",
        unknownLocationShort: "Posizione sconosciuta",
        photoTakenIn: "Questa foto è stata scattata a {place}",
        methodGPS: "Posizione identificata utilizzando le coordinate GPS dei metadati della foto.",
        moreInformation: "Scopri di più",
    },

    ja: {
        title: "写真ジオロケーター",
        welcome: "ようこそ！写真をアップロードして、撮影場所を特定しましょう。",
        upload: "写真をアップロード",
        searching: "場所を特定しています...",
        view: "表示",
        theme: "テーマ",
        language: "言語",
        satellite: "衛星",
        street: "道路",
        dark: "ダーク",
        light: "ライト",
        unknownLocation: "この写真の場所を特定できませんでした",
        unknownLocationShort: "不明な場所",
        photoTakenIn: "この写真は{place}で撮影されました",
        methodGPS: "写真のメタデータ内のGPS座標を使用して場所を特定しました。",
        moreInformation: "もっと知る",
    },

    ko: {
        title: "사진 위치 추적기",
        welcome: "환영합니다! 사진이 촬영된 위치를 확인하려면 사진을 업로드하세요.",
        upload: "사진 업로드",
        searching: "위치 확인 중...",
        view: "보기",
        theme: "테마",
        language: "언어",
        satellite: "위성",
        street: "거리",
        dark: "다크",
        light: "라이트",
        unknownLocation: "이 사진의 위치를 확인할 수 없습니다",
        unknownLocationShort: "알 수 없는 위치",
        photoTakenIn: "이 사진은 {place}에서 촬영되었습니다",
        methodGPS: "사진 메타데이터의 GPS 좌표를 사용하여 위치를 확인했습니다.",
        moreInformation: "자세히 보기",
    },

    lt: {
        title: "Nuotraukų geolokatorius",
        welcome: "Sveiki! Įkelkite nuotrauką, kad nustatytumėte, kur ji buvo padaryta.",
        upload: "Įkelti nuotrauką",
        searching: "Nustatoma vieta...",
        view: "Vaizdas",
        theme: "Tema",
        language: "Kalba",
        satellite: "Palydovas",
        street: "Gatvė",
        dark: "Tamsi",
        light: "Šviesi",
        unknownLocation: "Nepavyko nustatyti šios nuotraukos vietos",
        unknownLocationShort: "Nežinoma vieta",
        photoTakenIn: "Ši nuotrauka buvo padaryta {place}",
        methodGPS: "Vieta nustatyta naudojant GPS koordinates iš nuotraukos metaduomenų.",
        moreInformation: "Sužinoti daugiau",
    },

    lv: {
        title: "Fotoattēlu ģeolokators",
        welcome: "Laipni lūdzam! Augšupielādējiet fotoattēlu, lai noteiktu, kur tas uzņemts.",
        upload: "Augšupielādēt fotoattēlu",
        searching: "Notiek atrašanās vietas noteikšana...",
        view: "Skats",
        theme: "Tēma",
        language: "Valoda",
        satellite: "Satelīts",
        street: "Iela",
        dark: "Tumšs",
        light: "Gaišs",
        unknownLocation: "Šī fotoattēla atrašanās vietu neizdevās noteikt",
        unknownLocationShort: "Nezināma atrašanās vieta",
        photoTakenIn: "Šis fotoattēls tika uzņemts {place}",
        methodGPS: "Atrašanās vieta tika noteikta, izmantojot GPS koordinātas no fotoattēla metadatiem.",
        moreInformation: "Uzzināt vairāk",
    },

    nl: {
        title: "Foto-locatiezoeker",
        welcome: "Welkom! Upload een foto om te bepalen waar deze is genomen.",
        upload: "Foto uploaden",
        searching: "Locatie identificeren...",
        view: "Weergave",
        theme: "Thema",
        language: "Taal",
        satellite: "Satelliet",
        street: "Straat",
        dark: "Donker",
        light: "Licht",
        unknownLocation: "De locatie van deze foto kon niet worden geïdentificeerd",
        unknownLocationShort: "Onbekende locatie",
        photoTakenIn: "Deze foto is genomen in {place}",
        methodGPS: "Locatie geïdentificeerd met behulp van GPS-coördinaten uit de metadata van de foto.",
        moreInformation: "Meer informatie",
    },

    no: {
        title: "Foto-geolokator",
        welcome: "Velkommen! Last opp et bilde for å identifisere hvor det ble tatt.",
        upload: "Last opp bilde",
        searching: "Identifiserer sted...",
        view: "Visning",
        theme: "Tema",
        language: "Språk",
        satellite: "Satellitt",
        street: "Gate",
        dark: "Mørk",
        light: "Lys",
        unknownLocation: "Plasseringen til dette bildet kunne ikke identifiseres",
        unknownLocationShort: "Ukjent sted",
        photoTakenIn: "Dette bildet ble tatt i {place}",
        methodGPS: "Plasseringen ble identifisert ved hjelp av GPS-koordinater fra bildets metadata.",
        moreInformation: "Les mer",
    },

    pl: {
        title: "Geolokalizator zdjęć",
        welcome: "Witamy! Prześlij zdjęcie, aby określić, gdzie zostało wykonane.",
        upload: "Prześlij zdjęcie",
        searching: "Identyfikowanie lokalizacji...",
        view: "Widok",
        theme: "Motyw",
        language: "Język",
        satellite: "Satelita",
        street: "Ulica",
        dark: "Ciemny",
        light: "Jasny",
        unknownLocation: "Nie udało się zidentyfikować lokalizacji tego zdjęcia",
        unknownLocationShort: "Nieznana lokalizacja",
        photoTakenIn: "To zdjęcie zostało wykonane w {place}",
        methodGPS: "Lokalizacja została określona przy użyciu współrzędnych GPS z metadanych zdjęcia.",
        moreInformation: "Dowiedz się więcej",
    },

    pt: {
        title: "Geolocalizador de fotos",
        welcome: "Bem-vindo! Envie uma foto para identificar onde ela foi tirada.",
        upload: "Enviar foto",
        searching: "Identificando localização...",
        view: "Vista",
        theme: "Tema",
        language: "Idioma",
        satellite: "Satélite",
        street: "Rua",
        dark: "Escuro",
        light: "Claro",
        unknownLocation: "Não foi possível identificar a localização desta foto",
        unknownLocationShort: "Local desconhecido",
        photoTakenIn: "Esta foto foi tirada em {place}",
        methodGPS: "Local identificado usando as coordenadas GPS dos metadados da foto.",
        moreInformation: "Saiba mais",
    },

    ro: {
        title: "Geolocator foto",
        welcome: "Bun venit! Încarcă o fotografie pentru a identifica unde a fost făcută.",
        upload: "Încarcă fotografie",
        searching: "Se identifică locația...",
        view: "Vedere",
        theme: "Temă",
        language: "Limbă",
        satellite: "Satelit",
        street: "Stradă",
        dark: "Întunecat",
        light: "Deschis",
        unknownLocation: "Locația acestei fotografii nu a putut fi identificată",
        unknownLocationShort: "Locație necunoscută",
        photoTakenIn: "Această fotografie a fost făcută în {place}",
        methodGPS: "Locația a fost identificată folosind coordonatele GPS din metadatele fotografiei.",
        moreInformation: "Aflați mai multe",
    },

    ru: {
        title: "Геолокатор фотографий",
        welcome: "Добро пожаловать! Загрузите фотографию, чтобы определить, где она была сделана.",
        upload: "Загрузить фото",
        searching: "Определение местоположения...",
        view: "Вид",
        theme: "Тема",
        language: "Язык",
        satellite: "Спутник",
        street: "Улица",
        dark: "Тёмная",
        light: "Светлая",
        unknownLocation: "Не удалось определить местоположение этой фотографии",
        unknownLocationShort: "Неизвестное место",
        photoTakenIn: "Эта фотография была сделана в {place}",
        methodGPS: "Местоположение определено с помощью GPS-координат из метаданных фотографии.",
        moreInformation: "Подробнее",
    },

    sk: {
        title: "Geolokátor fotografií",
        welcome: "Vitajte! Nahrajte fotografiu a zistite, kde bola vytvorená.",
        upload: "Nahrať fotografiu",
        searching: "Identifikuje sa poloha...",
        view: "Pohľad",
        theme: "Téma",
        language: "Jazyk",
        satellite: "Satelit",
        street: "Ulica",
        dark: "Tmavý",
        light: "Svetlý",
        unknownLocation: "Polohu tejto fotografie sa nepodarilo identifikovať",
        unknownLocationShort: "Neznáme miesto",
        photoTakenIn: "Táto fotografia bola vytvorená v {place}",
        methodGPS: "Poloha bola identifikovaná pomocou GPS súradníc z metadát fotografie.",
        moreInformation: "Zistiť viac",
    },

    sl: {
        title: "Geolokator fotografij",
        welcome: "Dobrodošli! Naložite fotografijo, da ugotovite, kje je bila posneta.",
        upload: "Naloži fotografijo",
        searching: "Prepoznavanje lokacije...",
        view: "Pogled",
        theme: "Tema",
        language: "Jezik",
        satellite: "Satelit",
        street: "Ulica",
        dark: "Temna",
        light: "Svetla",
        unknownLocation: "Lokacije te fotografije ni bilo mogoče določiti",
        unknownLocationShort: "Neznana lokacija",
        photoTakenIn: "Ta fotografija je bila posneta v {place}",
        methodGPS: "Lokacija je bila določena z uporabo GPS-koordinat iz metapodatkov fotografije.",
        moreInformation: "Več informacij",
    },

    sr: {
        title: "Геолокатор фотографија",
        welcome: "Добро дошли! Отпремите фотографију да бисте идентификовали где је снимљена.",
        upload: "Отпреми фотографију",
        searching: "Идентификација локације...",
        view: "Приказ",
        theme: "Тема",
        language: "Језик",
        satellite: "Сателит",
        street: "Улица",
        dark: "Тамна",
        light: "Светла",
        unknownLocation: "Локација ове фотографије није могла бити идентификована",
        unknownLocationShort: "Непозната локација",
        photoTakenIn: "Ова фотографија је снимљена у {place}",
        methodGPS: "Локација је идентификована помоћу GPS координата из метаподатака фотографије.",
        moreInformation: "Сазнај више",
    },

    sv: {
        title: "Foto-geolokator",
        welcome: "Välkommen! Ladda upp ett foto för att identifiera var det togs.",
        upload: "Ladda upp foto",
        searching: "Identifierar plats...",
        view: "Vy",
        theme: "Tema",
        language: "Språk",
        satellite: "Satellit",
        street: "Gata",
        dark: "Mörk",
        light: "Ljus",
        unknownLocation: "Platsen för detta foto kunde inte identifieras",
        unknownLocationShort: "Okänd plats",
        photoTakenIn: "Detta foto togs i {place}",
        methodGPS: "Platsen identifierades med hjälp av GPS-koordinater från fotots metadata.",
        moreInformation: "Läs mer",
    },

    ta: {
        title: "புகைப்பட இடம் கண்டறிவி",
        welcome: "வரவேற்கிறோம்! படம் எங்கு எடுக்கப்பட்டது என்பதை கண்டறிய ஒரு புகைப்படத்தை பதிவேற்றவும்.",
        upload: "புகைப்படத்தை பதிவேற்று",
        searching: "இருப்பிடம் கண்டறியப்படுகிறது...",
        view: "காட்சி",
        theme: "தீம்",
        language: "மொழி",
        satellite: "செயற்கைக்கோள்",
        street: "தெரு",
        dark: "இருண்ட",
        light: "ஒளிரும்",
        unknownLocation: "இந்த புகைப்படத்தின் இருப்பிடத்தை கண்டறிய முடியவில்லை",
        unknownLocationShort: "தெரியாத இடம்",
        photoTakenIn: "இந்த புகைப்படம் {place} இல் எடுக்கப்பட்டது",
        methodGPS: "புகைப்படத்தின் மெட்டாடேட்டாவில் உள்ள GPS இணைக்கோட்டுகளை பயன்படுத்தி இருப்பிடம் கண்டறியப்பட்டது.",
        moreInformation: "மேலும் தகவல்",
    },

    th: {
        title: "ตัวระบุตำแหน่งภาพถ่าย",
        welcome: "ยินดีต้อนรับ! อัปโหลดรูปภาพเพื่อระบุว่าถ่ายที่ไหน",
        upload: "อัปโหลดรูปภาพ",
        searching: "กำลังระบุตำแหน่ง...",
        view: "มุมมอง",
        theme: "ธีม",
        language: "ภาษา",
        satellite: "ดาวเทียม",
        street: "ถนน",
        dark: "มืด",
        light: "สว่าง",
        unknownLocation: "ไม่สามารถระบุตำแหน่งของรูปภาพนี้ได้",
        unknownLocationShort: "ไม่ทราบตำแหน่ง",
        photoTakenIn: "รูปภาพนี้ถ่ายที่ {place}",
        methodGPS: "ระบุตำแหน่งโดยใช้พิกัด GPS จากข้อมูลเมตาของรูปภาพ",
        moreInformation: "ดูข้อมูลเพิ่มเติม",
    },

    tr: {
        title: "Fotoğraf konum bulucu",
        welcome: "Hoş geldiniz! Nerede çekildiğini belirlemek için bir fotoğraf yükleyin.",
        upload: "Fotoğraf yükle",
        searching: "Konum belirleniyor...",
        view: "Görünüm",
        theme: "Tema",
        language: "Dil",
        satellite: "Uydu",
        street: "Sokak",
        dark: "Koyu",
        light: "Açık",
        unknownLocation: "Bu fotoğrafın konumu belirlenemedi",
        unknownLocationShort: "Bilinmeyen konum",
        photoTakenIn: "Bu fotoğraf {place} konumunda çekildi",
        methodGPS: "Konum, fotoğraf meta verilerindeki GPS koordinatları kullanılarak belirlendi.",
        moreInformation: "Daha fazla bilgi",
    },

    uk: {
        title: "Геолокатор фотографій",
        welcome: "Ласкаво просимо! Завантажте фотографію, щоб визначити, де її було зроблено.",
        upload: "Завантажити фото",
        searching: "Визначення місцезнаходження...",
        view: "Перегляд",
        theme: "Тема",
        language: "Мова",
        satellite: "Супутник",
        street: "Вулиця",
        dark: "Темна",
        light: "Світла",
        unknownLocation: "Не вдалося визначити місцезнаходження цієї фотографії",
        unknownLocationShort: "Невідоме місце",
        photoTakenIn: "Цю фотографію було зроблено в {place}",
        methodGPS: "Місцезнаходження визначено за допомогою GPS-координат із метаданих фотографії.",
        moreInformation: "Дізнатися більше",
    },

    ur: {
        title: "تصویر جغرافیائی محل معلوم کرنے والا",
        welcome: "خوش آمدید! یہ معلوم کرنے کے لیے ایک تصویر اپ لوڈ کریں کہ یہ کہاں لی گئی تھی۔",
        upload: "تصویر اپ لوڈ کریں",
        searching: "مقام کی شناخت کی جا رہی ہے...",
        view: "دیکھیں",
        theme: "تھیم",
        language: "زبان",
        satellite: "سیٹلائٹ",
        street: "سڑک",
        dark: "گہرا",
        light: "ہلکا",
        unknownLocation: "اس تصویر کا مقام معلوم نہیں ہو سکا",
        unknownLocationShort: "نامعلوم مقام",
        photoTakenIn: "یہ تصویر {place} میں لی گئی تھی",
        methodGPS: "تصویر کے میٹا ڈیٹا میں موجود GPS نقاط استعمال کرکے مقام کی شناخت کی گئی۔",
        moreInformation: "مزید معلومات",
    },

    vi: {
        title: "Trình định vị ảnh",
        welcome: "Chào mừng! Tải lên một bức ảnh để xác định nơi nó được chụp.",
        upload: "Tải ảnh lên",
        searching: "Đang xác định vị trí...",
        view: "Chế độ xem",
        theme: "Giao diện",
        language: "Ngôn ngữ",
        satellite: "Vệ tinh",
        street: "Đường phố",
        dark: "Tối",
        light: "Sáng",
        unknownLocation: "Không thể xác định vị trí của bức ảnh này",
        unknownLocationShort: "Vị trí không xác định",
        photoTakenIn: "Bức ảnh này được chụp tại {place}",
        methodGPS: "Vị trí được xác định bằng tọa độ GPS từ siêu dữ liệu của ảnh.",
        moreInformation: "Tìm hiểu thêm",
    },

    zh: {
        title: "照片地理定位器",
        welcome: "欢迎！上传一张照片以识别拍摄地点。",
        upload: "上传照片",
        searching: "正在识别位置...",
        view: "视图",
        theme: "主题",
        language: "语言",
        satellite: "卫星",
        street: "街道",
        dark: "深色",
        light: "浅色",
        unknownLocation: "无法识别这张照片的位置",
        unknownLocationShort: "未知位置",
        photoTakenIn: "这张照片拍摄于{place}",
        methodGPS: "使用照片元数据中的 GPS 坐标识别了位置。",
        moreInformation: "了解更多",
    }
};

var languageInstructions = {
    en: "Respond with field values in English ONLY. Do not switch to any other language regardless of what text, signage, or visual context appears in the image. The user has selected English.",

    ar: "أجب بقيم الحقول باللغة العربية فقط. لا تنتقل إلى أي لغة أخرى مهما ظهر من نصوص أو لافتات أو سياق بصري في الصورة. لقد اختار المستخدم اللغة العربية.",

    bg: "Отговаряй със стойностите на полетата само на български. Не преминавай към друг език независимо от текста, табелите или визуалния контекст в изображението. Потребителят е избрал български език.",

    bn: "শুধুমাত্র বাংলায় ক্ষেত্রগুলোর মান প্রদান করুন। ছবিতে যেকোনো লেখা, সাইনবোর্ড বা ভিজ্যুয়াল প্রেক্ষাপট দেখা গেলেও অন্য কোনো ভাষায় পরিবর্তন করবেন না। ব্যবহারকারী বাংলা নির্বাচন করেছেন।",

    cs: "Odpovídej hodnotami polí pouze v češtině. Nepřepínej do jiného jazyka bez ohledu na text, značky nebo vizuální kontext na obrázku. Uživatel si vybral češtinu.",

    da: "Svar kun med felternes værdier på dansk. Skift ikke til noget andet sprog uanset tekst, skilte eller visuel kontekst i billedet. Brugeren har valgt dansk.",

    de: "Antworte mit den Feldwerten ausschließlich auf Deutsch. Wechsle nicht in eine andere Sprache, unabhängig davon, welcher Text, welche Beschilderung oder welcher visuelle Kontext im Bild erscheint. Der Nutzer hat Deutsch ausgewählt.",

    el: "Απάντησε με τις τιμές των πεδίων μόνο στα ελληνικά. Μην αλλάξεις σε άλλη γλώσσα ανεξάρτητα από το κείμενο, τις πινακίδες ή το οπτικό περιεχόμενο της εικόνας. Ο χρήστης έχει επιλέξει ελληνικά.",

    es: "Responde con los valores de los campos únicamente en español. No cambies a ningún otro idioma independientemente del texto, señales o contexto visual que aparezca en la imagen. El usuario ha seleccionado español.",

    et: "Vasta väljade väärtustega ainult eesti keeles. Ära vaheta teise keele peale olenemata sellest, milline tekst, märgistus või visuaalne kontekst pildil on. Kasutaja valis eesti keele.",

    fa: "فقط با مقادیر فیلدها به زبان فارسی پاسخ بده. صرف‌نظر از هر متن، تابلو یا محتوای تصویری موجود در تصویر، به زبان دیگری تغییر نده. کاربر زبان فارسی را انتخاب کرده است.",

    fi: "Vastaa kenttien arvoilla vain suomeksi. Älä vaihda mihinkään muuhun kieleen riippumatta siitä, mitä tekstiä, kylttejä tai visuaalista sisältöä kuvassa näkyy. Käyttäjä on valinnut suomen kielen.",

    fr: "Réponds avec les valeurs des champs uniquement en français. Ne passe à aucune autre langue, quel que soit le texte, les panneaux ou le contexte visuel présents dans l’image. L’utilisateur a sélectionné le français.",

    he: "השב עם ערכי השדות בעברית בלבד. אל תעבור לשפה אחרת ללא קשר לטקסט, לשילוט או להקשר החזותי שמופיעים בתמונה. המשתמש בחר בעברית.",

    hi: "फ़ील्ड के मान केवल हिंदी में दें। चित्र में चाहे कोई भी पाठ, संकेत या दृश्य संदर्भ दिखाई दे, किसी अन्य भाषा में स्विच न करें। उपयोगकर्ता ने हिंदी चुनी है।",

    hr: "Odgovori vrijednostima polja samo na hrvatskom jeziku. Nemoj prelaziti na drugi jezik bez obzira na tekst, znakove ili vizualni kontekst na slici. Korisnik je odabrao hrvatski.",

    hu: "A mezők értékeivel kizárólag magyarul válaszolj. Ne válts más nyelvre, függetlenül attól, milyen szöveg, felirat vagy vizuális környezet látható a képen. A felhasználó a magyart választotta.",

    id: "Berikan nilai field hanya dalam bahasa Indonesia. Jangan beralih ke bahasa lain apa pun teks, tanda, atau konteks visual yang muncul pada gambar. Pengguna telah memilih bahasa Indonesia.",

    is: "Svaraðu með gildum reitanna eingöngu á íslensku. Ekki skipta yfir á annað tungumál óháð texta, skiltum eða sjónrænu samhengi á myndinni. Notandinn hefur valið íslensku.",

    it: "Rispondi con i valori dei campi solo in italiano. Non passare a nessun'altra lingua indipendentemente dal testo, dalla segnaletica o dal contesto visivo presenti nell'immagine. L'utente ha selezionato l'italiano.",

    ja: "フィールドの値は日本語のみで回答してください。画像内にどのような文字、標識、視覚的な情報が含まれていても、他の言語に切り替えないでください。ユーザーは日本語を選択しています。",

    ko: "필드 값은 한국어로만 응답하세요. 이미지에 어떤 텍스트, 표지판 또는 시각적 맥락이 나타나더라도 다른 언어로 전환하지 마세요. 사용자가 한국어를 선택했습니다.",

    lt: "Atsakyk laukų reikšmėmis tik lietuvių kalba. Nepereik į kitą kalbą, nepaisant paveikslėlyje esančio teksto, ženklų ar vaizdinio konteksto. Vartotojas pasirinko lietuvių kalbą.",

    lv: "Atbildi ar lauku vērtībām tikai latviešu valodā. Nepārslēdzies uz citu valodu neatkarīgi no attēlā redzamā teksta, zīmēm vai vizuālā konteksta. Lietotājs ir izvēlējies latviešu valodu.",

    nl: "Antwoord uitsluitend met de veldwaarden in het Nederlands. Schakel niet over naar een andere taal, ongeacht welke tekst, borden of visuele context in de afbeelding verschijnen. De gebruiker heeft Nederlands geselecteerd.",

    no: "Svar kun med feltverdiene på norsk. Ikke bytt til noe annet språk uansett hvilken tekst, skilting eller visuell kontekst som vises i bildet. Brukeren har valgt norsk.",

    pl: "Odpowiadaj wartościami pól wyłącznie po polsku. Nie przełączaj się na inny język niezależnie od tekstu, znaków lub kontekstu wizualnego widocznego na obrazie. Użytkownik wybrał język polski.",

    pt: "Responda com os valores dos campos somente em português brasileiro. Não mude para nenhum outro idioma, independentemente do texto, das placas ou do contexto visual presentes na imagem. O usuário selecionou português brasileiro.",

    ro: "Răspunde cu valorile câmpurilor numai în limba română. Nu trece la altă limbă indiferent de textul, semnele sau contextul vizual din imagine. Utilizatorul a selectat limba română.",

    ru: "Отвечай значениями полей только на русском языке. Не переключайся на другой язык независимо от текста, вывесок или визуального контекста на изображении. Пользователь выбрал русский язык.",

    sk: "Odpovedaj hodnotami polí iba v slovenčine. Neprepínaj sa do iného jazyka bez ohľadu na text, značky alebo vizuálny kontext na obrázku. Používateľ si vybral slovenčinu.",

    sl: "Odgovori z vrednostmi polj samo v slovenščini. Ne preklapljaj v drug jezik ne glede na besedilo, znake ali vizualni kontekst na sliki. Uporabnik je izbral slovenščino.",

    sr: "Одговори вредностима поља искључиво на српском језику. Не прелази на други језик без обзира на текст, знакове или визуелни контекст на слици. Корисник је изабрао српски језик.",

    sv: "Svara endast med fältvärdena på svenska. Byt inte till något annat språk oavsett vilken text, skyltning eller visuell kontext som visas i bilden. Användaren har valt svenska.",

    ta: "புலங்களின் மதிப்புகளை தமிழில் மட்டும் பதிலளிக்கவும். படத்தில் எந்த உரை, பலகை அல்லது காட்சி சூழல் இருந்தாலும் வேறு மொழிக்கு மாற வேண்டாம். பயனர் தமிழைத் தேர்ந்தெடுத்துள்ளார்.",

    th: "ตอบกลับค่าของฟิลด์เป็นภาษาไทยเท่านั้น ห้ามเปลี่ยนเป็นภาษาอื่นไม่ว่าภาพจะมีข้อความ ป้าย หรือบริบททางภาพใด ๆ ผู้ใช้ได้เลือกภาษาไทยไว้แล้ว",

    tr: "Alan değerleriyle yalnızca Türkçe olarak yanıt ver. Görselde hangi metin, tabela veya görsel bağlam bulunursa bulunsun başka bir dile geçme. Kullanıcı Türkçeyi seçti.",

    uk: "Відповідай значеннями полів лише українською мовою. Не переходь на іншу мову незалежно від тексту, знаків чи візуального контексту на зображенні. Користувач обрав українську мову.",

    ur: "فیلڈز کی قدریں صرف اردو میں فراہم کریں۔ تصویر میں چاہے کوئی بھی متن، سائن یا بصری سیاق موجود ہو، کسی دوسری زبان میں تبدیل نہ ہوں۔ صارف نے اردو منتخب کی ہے۔",

    vi: "Trả lời với các giá trị trường chỉ bằng tiếng Việt. Không chuyển sang bất kỳ ngôn ngữ nào khác bất kể văn bản, biển báo hay ngữ cảnh hình ảnh xuất hiện trong ảnh. Người dùng đã chọn tiếng Việt.",

    zh: "请仅使用中文填写字段值。无论图片中出现什么文字、标识或视觉内容，都不要切换到其他语言。用户已选择中文。",
};

function translate(key) {
    return TRANSLATIONS[currentLang][key] || TRANSLATIONS.en[key] || key;
}

function changeLanguage() {

    document.title = "🌍 " + translate("title");

    document.getElementById("welcome").textContent = translate("welcome");

    document.getElementById("searchingText").innerHTML = " " + translate("searching");

    document.getElementById("imageInputLabel").textContent = translate("upload");

    document.getElementById("imageInputLabelPanel").textContent = translate("upload");

    document.getElementById("showToggleView").innerHTML = translate("view") + " ▼";

    if (!isSatellite) document.getElementById("toggleView").textContent = translate("satellite");
    else document.getElementById("toggleView").textContent = translate("street");

    document.getElementById("showToggleTheme").innerHTML = translate("theme") + " ▼";

    if (!isDark) document.getElementById("toggleTheme").textContent = translate("dark");
    else document.getElementById("toggleTheme").textContent = translate("light");

    document.getElementById("showToggleLanguage").innerHTML = translate("language") + " ▼";

    document.getElementById("learnMore").innerHTML = translate("moreInformation") + " ▼";

}
